/**
 * Expo config plugin: migrate the iOS app to the UIScene life cycle.
 *
 * iOS 27 / Xcode 27 require apps to adopt the UIScene life cycle (Apple Technote
 * TN3187) — otherwise launch fails with "UIScene life cycle is required for apps
 * built with this SDK". The Expo SDK 56 prebuild template still generates the
 * classic `UIApplicationDelegate` + `UIWindow(frame:)` setup, so this plugin
 * re-applies the migration on every `expo prebuild` (the native `ios/` dir is
 * git-ignored under Continuous Native Generation and is regenerated each time):
 *
 *   1. Info.plist  — declare a scene configuration pointing at `SceneDelegate`.
 *   2. AppDelegate — stop creating the window / starting RN here; just capture
 *      `launchOptions` for the scene to consume.
 *   3. SceneDelegate.swift — written into the project; creates the scene-bound
 *      window, starts React Native into it, and preserves deep-link delivery.
 *   4. project.pbxproj — register SceneDelegate.swift in the app target.
 *
 * NOTE: Why deep links need care. Expo SDK 56's `ExpoAppDelegate` has no scene
 * support, and expo-linking / expo-router hook the *app-delegate* URL methods.
 * Under the scene life cycle iOS routes those to the *scene* delegate instead, so
 * the generated SceneDelegate forwards warm opens back into the AppDelegate, and
 * injects a cold-launch URL into the launch options it hands to RN (the only
 * place `RCTLinkingManager.getInitialURL` reads from) — keeping the
 * `fetchitmobile://join-family?token=…` family-invite flow working.
 */
const {
  withInfoPlist,
  withAppDelegate,
  withDangerousMod,
  withXcodeProject,
  IOSConfig,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SCENE_DELEGATE_SWIFT = `import UIKit
import React

// Adopts the UIScene life cycle required by iOS 27 / Xcode 27 (Apple Technote
// TN3187). The window — previously created in \`AppDelegate\` — is now created and
// owned here, bound to the connecting \`UIWindowScene\`, and React Native is
// started into it via the factory the \`AppDelegate\` set up at launch.
//
// Generated by plugins/withSceneLifecycle.js — edit the plugin, not this file
// (it is regenerated on every \`expo prebuild\`).
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = UIApplication.shared.delegate as? AppDelegate,
          let factory = appDelegate.reactNativeFactory else { return }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    // Mirror the window onto the AppDelegate too: React Native and some libraries
    // still resolve the app window via \`UIApplication.delegate.window\`, and leaving
    // it nil breaks touch/interaction delivery and the orientation path. This is the
    // critical line that keeps the migrated app responsive.
    appDelegate.window = window

    // Under the scene life cycle a deep link / universal link that *cold-launches*
    // the app arrives in \`connectionOptions\`, NOT in the app delegate's launch
    // options. \`RCTLinkingManager.getInitialURL\` reads the URL exclusively from
    // the bridge's launch options, so inject it there — otherwise a cold start
    // from \`fetchitmobile://join-family?token=…\` (the family-invite flow, which
    // depends on \`Linking.getInitialURL()\`) would be lost. Doing it this way
    // matches the classic life cycle, where a launch URL populates \`getInitialURL\`
    // and does NOT also fire a \`url\` event.
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = appDelegate.launchOptions ?? [:]
    if let url = connectionOptions.urlContexts.first?.url {
      launchOptions[.url] = url
    } else if let userActivity = connectionOptions.userActivities.first(
      where: { $0.activityType == NSUserActivityTypeBrowsingWeb }
    ) {
      launchOptions[.userActivityDictionary] = [
        UIApplication.LaunchOptionsKey.userActivityType.rawValue: userActivity.activityType,
        // Key string \`RCTLinkingManager.getInitialURL\` reads the activity from.
        "UIApplicationLaunchOptionsUserActivityKey": userActivity,
      ]
    }

    // \`startReactNative(...)\` sets the window's rootViewController and calls
    // \`makeKeyAndVisible\`, so no extra window setup is needed here.
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions
    )
    // \`startReactNative\` already makes the window key+visible, but call it
    // explicitly to match the canonical RN scene setup and guard against any
    // factory override that skips it.
    window.makeKeyAndVisible()
  }

  // Foreground deep link (app already running) — fire the \`url\` event path.
  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let url = URLContexts.first?.url else { return }
    forwardOpenURL(url)
  }

  // Foreground universal link (app already running).
  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    forwardUserActivity(userActivity)
  }

  // Forward to the \`AppDelegate\` so both React Native's \`RCTLinkingManager\`
  // (which posts the \`url\` event) and Expo's app-delegate subscribers
  // (expo-linking / expo-router) are notified — Expo SDK 56 does not yet forward
  // scene events to its subscriber chain.
  private func forwardOpenURL(_ url: URL) {
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
    _ = appDelegate.application(UIApplication.shared, open: url, options: [:])
  }

  private func forwardUserActivity(_ userActivity: NSUserActivity) {
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
    _ = appDelegate.application(UIApplication.shared, continue: userActivity) { _ in }
  }
}
`;

/**
 * Rewrite the Expo-generated Swift AppDelegate so it no longer *creates* the
 * window — that moves to `SceneDelegate`. The `var window` property is KEPT
 * (and `SceneDelegate` assigns the scene window back onto it), because React
 * Native and some libraries still resolve the app window via
 * `UIApplication.delegate.window`; leaving it nil breaks touch delivery. Throws
 * if the expected template shape isn't found, so a future Expo SDK bump fails
 * loudly here instead of silently shipping a broken app.
 */
function transformAppDelegate(contents) {
  // Idempotent — bail if already migrated (e.g. plugin applied twice).
  if (contents.includes('var launchOptions:')) {
    return contents;
  }

  let next = contents;

  // NOTE: `var window: UIWindow?` is intentionally left in place — SceneDelegate
  // mirrors the scene's window onto it so `UIApplication.delegate.window` resolves.

  // Store launchOptions so SceneDelegate can start RN when its scene connects.
  if (!/var reactNativeFactory: RCTReactNativeFactory\?/.test(next)) {
    throw new Error(
      '[with-scene-lifecycle] Could not find the `reactNativeFactory` property in ' +
        'AppDelegate.swift — the Expo template changed; update plugins/withSceneLifecycle.js.'
    );
  }
  next = next.replace(
    /([ \t]*var reactNativeFactory: RCTReactNativeFactory\?)/,
    '$1\n  var launchOptions: [UIApplication.LaunchOptionsKey: Any]?'
  );

  // Remove the AppDelegate-owned window *setup*; just capture launchOptions.
  const windowBlock =
    /\n#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\([\s\S]*?\)\n#endif\n/;
  if (!windowBlock.test(next)) {
    throw new Error(
      '[with-scene-lifecycle] Could not find the window/startReactNative block in ' +
        'AppDelegate.swift — the Expo template changed; update plugins/withSceneLifecycle.js.'
    );
  }
  next = next.replace(windowBlock, '\n    self.launchOptions = launchOptions\n');

  return next;
}

const withSceneInfoPlist = (config) =>
  withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return cfg;
  });

const withSceneAppDelegate = (config) =>
  withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `[with-scene-lifecycle] Expected a Swift AppDelegate but found "${cfg.modResults.language}".`
      );
    }
    cfg.modResults.contents = transformAppDelegate(cfg.modResults.contents);
    return cfg;
  });

const withSceneDelegateFile = (config) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const dest = path.join(
        cfg.modRequest.platformProjectRoot,
        cfg.modRequest.projectName,
        'SceneDelegate.swift'
      );
      await fs.promises.writeFile(dest, SCENE_DELEGATE_SWIFT, 'utf8');
      return cfg;
    },
  ]);

const withSceneDelegateInXcodeProject = (config) =>
  withXcodeProject(config, (cfg) => {
    const projectName = cfg.modRequest.projectName;
    IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
      filepath: `${projectName}/SceneDelegate.swift`,
      groupName: projectName,
      project: cfg.modResults,
    });
    return cfg;
  });

/** @param {import('expo/config').ExpoConfig} config */
module.exports = function withSceneLifecycle(config) {
  config = withSceneInfoPlist(config);
  config = withSceneAppDelegate(config);
  config = withSceneDelegateFile(config);
  config = withSceneDelegateInXcodeProject(config);
  return config;
};

// Exposed for unit testing the AppDelegate rewrite.
module.exports.transformAppDelegate = transformAppDelegate;
module.exports.SCENE_DELEGATE_SWIFT = SCENE_DELEGATE_SWIFT;
