import { ScrollView, StyleSheet } from 'react-native';

import { Bold, Bullets, Closing, Dates, H1, H2, H3, P } from '@/components/Prose';
import { Screen } from '@/components/ui/Screen';
import { Spacing } from '@/theme/colors';

// Public Privacy Policy — full port of the web app's PrivacyPolicyPage.js. No
// login required; the header (title + back) is provided by the root Stack.Screen.
export default function PrivacyPolicyScreen() {
  return (
    <Screen>
      <ScrollView contentContainerStyle={styles.scroll}>
        <H1>FetchIt Privacy Policy</H1>
        <Dates effective="June 13, 2026" updated="June 13, 2026" />

        <P>
          This Privacy Policy explains how FetchIt collects, uses, stores, shares,
          and protects your personal information when you use the FetchIt
          platform, website, mobile application, or any related services. By using
          the Service, you agree to the collection and use of your information as
          described in this Privacy Policy.
        </P>

        <H2>1. Information We Collect</H2>

        <H3>1.1 Information You Provide Directly</H3>
        <Bullets
          items={[
            'Account information: name, email address, password or Google account details',
            'Shipping address: full name, address lines, city, state, ZIP, country',
            'Payment information: non-sensitive card metadata only (brand, last 4 digits, expiry) — full card details handled exclusively by Stripe',
            'Display name chosen during onboarding',
            'Messages and requests sent through the Service',
          ]}
        />

        <H3>1.2 Information Generated by Your Use</H3>
        <Bullets
          items={[
            'Chat and conversation history — every message sent to the FetchIt AI assistant',
            'Order history — product name, retailer, price, service fee, status, category',
            'Usage data — token usage per session and weekly totals',
            'Shopping preferences inferred from searches and purchases',
            'Device and technical information — browser type, IP address, OS, access times',
          ]}
        />

        <H3>1.3 Information from Third Parties</H3>
        <Bullets
          items={[
            'Google — name, email, profile picture if you sign in with Google',
            'Stripe — payment confirmation and non-sensitive card metadata',
            'Zinc Technologies — order confirmation, tracking, and return status',
          ]}
        />

        <H2>2. How We Use Your Information</H2>
        <Bullets
          items={[
            'To provide the Service — processing searches, placing orders, managing your account',
            'To communicate with you — order confirmations, shipping updates, security emails',
            'To process payments — charging your saved payment method via Stripe',
            'To enforce usage limits — tracking token consumption per plan',
            'To improve the Service — analyzing usage patterns to improve features',
            'To comply with legal obligations',
          ]}
        />

        <H2>3. AI Training and Data Sharing with xAI</H2>
        <P>
          <Bold>This section requires your careful attention.</Bold>
        </P>
        <P>
          FetchIt uses Grok 4.3, developed and operated by xAI, Inc., to power its
          shopping assistant.
        </P>
        <P>By using FetchIt, you acknowledge and agree that:</P>
        <Bullets
          items={[
            'Your conversations with the FetchIt AI assistant — including search queries, product requests, shopping preferences, purchase history, and all chat interactions — may be transmitted to xAI and used by xAI and its affiliates to train, improve, fine-tune, and develop their artificial intelligence models.',
            "This data sharing occurs as a condition of FetchIt's use of xAI's API services.",
            'You cannot opt out of this data sharing while using the Service. If you do not consent to your conversation data being used to train AI models, you must not use the Service.',
            "FetchIt does not control how xAI uses your data beyond what is described in xAI's own Privacy Policy at x.ai/privacy.",
            'Data shared with xAI may include personal details mentioned in conversation, such as gift recipient names and personal preferences.',
          ]}
        />
        <P>
          We strongly recommend you do not share sensitive personal information
          (Social Security numbers, full financial account numbers, medical
          information) in the FetchIt chat interface.
        </P>

        <H2>4. How We Share Your Information</H2>
        <P>
          We do not sell your personal information to advertisers or third-party
          data brokers. We share information only with:
        </P>
        <Bullets
          items={[
            'Supabase — database hosting and authentication',
            'Stripe — payment processing and subscription management',
            'Zinc Technologies — order placement, tracking, and returns',
            'xAI — AI inference and model training as described in Section 3',
            'Resend — transactional email delivery',
            'Retailers — your shipping address and order details are shared with applicable retailers (Amazon, Walmart, etc.) through Zinc to fulfill your orders',
            'Legal authorities — if required by law or to protect rights and safety',
            'Business transfers — if FetchIt is acquired or merged',
          ]}
        />

        <H2>5. Data Retention</H2>
        <Bullets
          items={[
            'Account data: retained until you delete your account',
            'Order history: retained for 7 years for tax and legal compliance',
            'Chat history: retained until you delete chats or your account',
            'Usage data: retained for 13 months',
            'On account deletion, personal data is deleted within 30 days except where required by law',
          ]}
        />

        <H2>6. Data Security</H2>
        <Bullets
          items={[
            'All data transmitted over encrypted HTTPS',
            'Payment card details never stored on our servers — handled by Stripe (PCI DSS compliant)',
            'Shipping addresses stored in Supabase with Row Level Security',
            'Sensitive pages require password or Google reauthentication',
            'No method of transmission is 100% secure — we cannot guarantee absolute security',
          ]}
        />

        <H2>7. Your Rights and Choices</H2>
        <Bullets
          items={[
            'Access: view your account info, orders, and analytics within the Service',
            'Correction: update name, address, and payment method in account settings',
            'Deletion: delete your account anytime through account settings',
            'Marketing emails: unsubscribe via link in any marketing email',
            'AI training: you cannot opt out of xAI training while using the Service',
          ]}
        />

        <H2>8. Cookies and Tracking</H2>
        <P>
          FetchIt uses localStorage and sessionStorage for session preferences and
          UI state. We do not use advertising cookies or third-party tracking
          pixels.
        </P>

        <H2>9. Children's Privacy</H2>
        <P>
          The Service is not directed at children under 18. We do not knowingly
          collect information from anyone under 18. Contact support@fetchit.com if
          you believe we have collected information from a minor.
        </P>

        <H2>10. International Users</H2>
        <P>
          FetchIt is operated from the United States and is currently available to
          US users only. Your information will be stored and processed in the
          United States.
        </P>

        <H2>11. Third-Party Links</H2>
        <P>
          This Privacy Policy does not apply to third-party websites linked from
          the Service. Review the privacy policies of any third-party sites you
          visit.
        </P>

        <H2>12. Changes to This Privacy Policy</H2>
        <P>
          We will notify you of material changes by updating the Last Updated date
          and sending email notification where appropriate. Continued use
          constitutes acceptance.
        </P>

        <H2>13. Contact Us</H2>
        <P>FetchIt — Email: support@fetchit.com</P>

        <Closing>
          By using FetchIt, you acknowledge that you have read this Privacy Policy
          and understand how your information is collected, used, and shared.
        </Closing>
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  scroll: { paddingVertical: Spacing.lg, paddingBottom: Spacing.xxl },
});
